---
title: "GroupProject"
author: "Group 29"
date: "10/18/2020"
output: html_document
---
```{r, loadinglibs}
library(vroom)
library(dplyr)
library(skimr)
library(tidyverse)
library(mosaic)
library(janitor)
library(skimr)
library(broom)
library(lubridate)
library(GGally)
library(leaflet)
library(ggfortify)
library(huxtable)
library(car)
library(kableExtra)
library(data.table)
library(modelr)
library(readr)
```



## Loading Data

First we are going to read the data directly from the URL:
```{r}
listings <- vroom::vroom("http://data.insideairbnb.com/china/hk/hong-kong/2020-06-15/data/listings.csv.gz", na=c("", "NA"))%>%
  clean_names()
```


# Exploratory Data Analysis (EDA)

## Looking at the raw values

### How many variables/columns? How many rows/observations?

We have 106 variables and 11,187 observations.

```{r}
glimpse(listings)
```

## Which variables are numbers?

1. 

```{r}
skim(listings)%>%
  kable()%>%
  kable_styling()
```




```{r}
intersting_data <- listings %>%
  select(c(1, 2, host_since, host_response_time, host_response_rate, host_is_superhost, neighbourhood, host_listings_count, host_has_profile_pic, host_identity_verified, neighbourhood_cleansed, city, latitude, longitude, is_location_exact, property_type, room_type, accommodates, bathrooms, bedrooms, beds, bed_type, price, security_deposit, cleaning_fee, guests_included, extra_people, minimum_nights, maximum_nights, has_availability, number_of_reviews, number_of_reviews_ltm, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, instant_bookable, cancellation_policy, reviews_per_month))


main_data <- intersting_data %>%
  mutate(host_response_rate = parse_number(host_response_rate),
         price = parse_number(price),
         security_deposit = parse_number(security_deposit),
         cleaning_fee = parse_number(cleaning_fee),
         extra_people = parse_number(extra_people))%>%
  filter(has_availability == TRUE, minimum_nights <= 4, maximum_nights >= 4)

skim(main_data)
```


```{r}
favstats(main_data)
```

